@host = https://localhost:7226

GET {{host}}/serilog/overrides
Accept: application/json

###

PUT {{host}}/serilog/debug

###

POST {{host}}/serilog/query

###

POST {{host}}/serilog/query
Content-type: application/json
{
  "Criteria": {
    "Level":"Information",
    "Properties": {
      "SourceContext":"Microsoft.EntityFrameworkCore.Database.Command"
    },
    "Skip": 0,
    "Take": 10
  }  
}

###

POST {{host}}/serilog/query
Content-type: application/json
{
  "Criteria": {
    "Level":"Information"    
  }  
}
