<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>    
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QueryApi\QueryApi.csproj" />
    <ProjectReference Include="..\QueryApi.MySql\QueryApi.MySql.csproj" />
    <ProjectReference Include="..\LevelApi\LevelApi.csproj" />
    <ProjectReference Include="..\LevelApi.MySql\LevelApi.MySql.csproj" />
    <ProjectReference Include="..\SerilogUtil\SerilogUtil.csproj" />
  </ItemGroup>

</Project>
